version: "3"

services:
  suitecrm:
    build: .
    container_name: suitecrm
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    environment:
      - DB_TYPE=mysql
      - DB_MANAGER=MysqlManager
      - DB_TCP_PORT=3307

  db:
    image: mariadb:5.5.57
    container_name: suitecrm_db
    volumes:
      - suitecrm-volume:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=suitecrm
      - MYSQL_DATABASE=suitecrm
      - MYSQL_USER=suitecrm
      - MYSQL_PASSWORD=suitecrm

volumes:
  suitecrm-volume:
