suitecrm:
  build: 7.1.6
  ports:
    - "2080:80"
  links:
    - "db"
  environment:
    DB_TYPE: mysql
    DB_MANAGER: MysqlManager
dbdata:
  image: tianon/true
  volumes:
    - /my/volume
db:
  image: mariadb
  volumes_from:
    - dbdata
  environment:
    MYSQL_ROOT_PASSWORD: YZiT4p7BXUqpdgpc
    MYSQL_DATABASE: suitecrm
    MYSQL_USER: suitecrm
    MYSQL_PASSWORD: password